# The OCR service to use. Options: "google", "azure", "aws"
service: google

# Azure AI Vision credentials (only required if service is 'azure')
azure_endpoint: "https://wz-computer-vision.cognitiveservices.azure.com/"
azure_key: "YOUR_AZURE_KEY"

# Optional: Path to the output directory where OCR results will be saved.
# If not specified, results will be saved in the same directory as the input PDF.
# Example: output_file_path: /Users/wwzhang/Documents/output_ocr/
output_file_path: 

# Optional: Path to Google Cloud service account key file (only required if service is 'google' and not using Application Default Credentials).
google_credentials_path: leafy-pilot-475823-j8-0f86bd078e30.json
